:ruby: ree187
:application: super
:user: rails
#:time_zone: UTC
:deploy_to: /var/www/apps/super
:domain: supersofar.com
:domain_aliases:
  - www.supersofar.com

:repository: git@github.com:electricgraffitti/supersofar.git
:branch: master
# Use :app_symlinks to setup directories under public/ that you want to persist
# across deployments. They'll be symlinked to the shared directory.
:app_symlinks:
  - album_covers
  - attachments
  - songs
  - photos
  - link_images
  - avatars
  - fan_photos
#
# Use :local_config to copy directories straight from your local project directory
# to the server: these are files that you don't have/want in scm.
:local_config:
  - config/database.yml
#
# The entries in shared_children are created in #{application}/shared
:shared_children:
- system
- log
- pids
- config
# After specifying a gem with config.gem, run 'rake moonshine:gems'
# to update config/gems.yml. If the gem depends on native packages, 
# tell Moonshine here:
:apt_gems:
  :paperclip:
    - imagemagick
  #    - libawesome-dev
#
# See all the options for Passenger, Apache vhosts, and MySQL in the
# respective templates: moonshine/lib/moonshine/manifest/rails/templates
:passenger:
  :max_pool_size: 2
  :use_global_queue: true
  :version: 2.2.15
:mysql:
  :innodb_buffer_pool_size: 128M
